on:
  workflow_dispatch:

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    container: ghcr.io/eebssk1/bbk/debian-bookworm:0.1

    steps:
      - uses: actions/checkout@v1
      - name: dep
        run: |
          apt-get update
          apt-get upgrade -y
          apt-get install uuid-runtime -y
      - name: enable ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          verbose: 1
          max-size: "1872M"
      - name: clone
        run: git clone --single-branch -b master https://git.code.sf.net/p/mingw-w64/mingw-w64 mingw-w64-mingw-w64
      - name: pre
        run: ./pre.sh
      - name: env data
        run: |
          export thetag=$(cat tag)
          export thetime=$(cat time)
          echo "my_tag=$thetag" >> $GITHUB_ENV
          echo "my_time<<ENDR" >> $GITHUB_ENV
          echo "$thetime" >> $GITHUB_ENV
          echo "ENDR" >> $GITHUB_ENV
      - name: build64
        run: ./build64.sh
      - name: build32
        run: ./build32.sh
      - name: pack
        run: ./pack.sh
      - name: upload
        uses: actions/upload-artifact@v3.1.2
        with:
          path: ./mingw-crt
      - name: release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: ./mingw-crt.tgz
          body: ${{ env.my_time }}
          commit: main
          makeLatest: true
          name: build_${{ env.my_tag }}
          tag: ${{ env.my_tag }}
